import type { Metadata } from "next";
import { Bricolage_Grotesque, Figtree, Instrument_Serif, Inter } from "next/font/google"
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider"
import { cn } from "@/lib/utils";

const figtreeHeading = Figtree({ subsets: ["latin"], variable: "--font-heading", display: "swap" });

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
  display: "swap",
})

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  variable: "--font-instrument-serif",
  display: "swap",
  weight: ["400"], // esta familia suele ser 400
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={cn(bricolage.variable, instrumentSerif.variable, "font-sans", inter.variable, figtreeHeading.variable)}>
      <body className="font-sans antialiased">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
